yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'group_namespace'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/slug:slug/', views.group_posts, name='group_posts'),
]   

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='group_namespace')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
        title = models.TextField()
        slug = models.SlugField(unique=True)
        description = models.TextField()
        def __str__(self):
            return self.title

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        null = True,
        blank = True,
        related_name = 'group_posts',
    )

yatube/posts/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Post
from .models import Group

# Create your views here.


#Главная страница
def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    title = 'Последние новости'
    context = {
        'title':title,
        'text':'Это главная страница проекта Yatube',
        'posts':posts,
    }
    return render(request, 'posts/index.html', context)

#template = ('index.html/') return render(request, template, {})

#Страница сообществ
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    # Функция get_object_or_404 получает по заданным критериям объект 
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    title = 'Список сообществ'
    context = {
        'title':title,
        'text':'Здесь будет информация о группах проекта Yatube',
        'group':group,
        'posts':posts,
    }
    return render(request, 'posts/group_list.html', context)
    #return HttpResponse(f'Сообщество {slug}')

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru">          
  <head>
  <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        Главная страница
      {% endblock title %}
    </title>          
  </head>
    <body>       
      <header>
        {% include 'includes/header.html' %}
      </header>   
      <main>
        {% block content%}
        Информация на главной странице  
        {% endblock content%}
    </header>
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %} 
    </footer>
  </body
</html>   
  

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
<p>© 2021 Copyright <span style="color:red">Ya</span>tube</p> 

yatube/templates/includes/header.html
{% load static %}
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
        <a class="navbar-brand" href="{% url 'group_namespace:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt=""> 
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube</a>
        </a>
    </div>
</nav>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content%}
  Здесь будет информация о группах проекта Yatube
{% endblock %}
  <body>
    <header>
      {% include 'includes/header.html' %}     
    </header>
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <p>{{ group.title }}</p>
        <h1>{{ group.description }}</h1>
        {% for post in posts %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{post.pub_date|date:"j F Y"}}
            </li>
          </ul>      
          <p>
           {{ post.text }}
          </p>
          {%if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      </div>
{% endblock %}        
      </div>  
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}   
    </footer>
  </body>
  

yatube/templates/posts/index.html
{% extends 'base.html'%}
{% block title%}
    Последние новости
{% endblock %}      
  <body>
    <header>
      {% include 'includes/header.html' %}     
    </header>
    <main>
{%block content%} 
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <h1>{{ title }}</h1>
        {% for post in posts %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{post.pub_date|date:"j F Y"}}
            </li>
          </ul>      
          <p>
           {{ post.text }}
          </p>
          <a href="{% url 'group_namespace:group_posts' post.group.slug %}">все записи группы</a>
          {%if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      </div>
{% endblock %}        
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}  
    </footer>
  </body>